### ISSUE TITLE
Toolchain reliance on Windows/Linux-only IAR tools prevents macos compatibility

### ISSUE THREAD

**Issue by chris-hatton** [ambiot/amb1_sdk#2]
The Ameba SDK is _almost_ macos compatible; invocations of `gcc` and other common tools during compilation stage all work as expected.  However the final stage of binary preparation is reliant on `pick` and other IAR tools which are provided as binaries and only for Windows/Linux.

These are at relative paths:
- `component/soc/realtek/8711b/misc/iar_utility/common/tools`
- `component/soc/realtek/8195a/misc/iar_utility/common/tools`

SDK scripts attempt to invoke the Linux `pick` binary at this stage and fail.

These tools **are available** as part of the Ameba Arduino toolchain.  It's unclear where these were sourced from: perhaps directly from Realtek?  Adopting the more clearly organised `ameba_tools_*` folders from this Arduino toolchain and updating scripts to suit, may make `amb1_sdk` macos compatible with relatively little effort.

**Comment by xidameng** [comment]
Hi Chris,

Thanks for the feedback, I have just checked compiling for Ameba 1 using IAR version 7.8, everything seems working fine, no error report.

However, you are right about the `pick` for linux, it shouldn't be there in the first place.
